[package]
name = "historygen"
version = "0.1.0"
edition = "2021"

[dependencies]
string_template = "0.2.1"
mongodb = { version = "2.3.0", features = ["tokio-sync"] }
bson = { version = "2", features = ["chrono-0_4"] }
chrono = "0.4"
rand = "0.8.5"
rouille = "3.5.0"